authentication/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from .views import (CompletePasswordReset, EmailValidationView, LoginView,
                    LogoutView, RegistrationView, RequestPasswordResetEmail,
                    UsernameValidationView, VerificationView)

app_name = 'authentication'

urlpatterns = [
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('registration/validate-username/', csrf_exempt(UsernameValidationView.as_view()),
         name='validate-username'),

    path('registration/validate-email/', csrf_exempt(EmailValidationView.as_view()),
         name='validate-email'),
    path('registration/activate/<uidb64>/<token>/',
         VerificationView.as_view(), name='activate'),
    path('request-reset-link/', RequestPasswordResetEmail.as_view(),
         name='request-password'),
    path('set-new-password/<uidb64>/<token>/',
         CompletePasswordReset.as_view(), name='set-new-password'),


]

expense/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from . import views

app_name = 'expense'

urlpatterns = [
    path('', views.home, name='home'),
    path('add/expense/', views.addExpense, name='addExpense'),
    path('edit/expense/<int:id>/', views.editExpense, name='editExpense'),
    path('delete/expense/<int:id>/', views.deleteExpense, name='deleteExpense'),
    path('search-expenses/', csrf_exempt(views.searchExpense), name='searchExpense'),
    path('get-category/<int:category_id>/',
         csrf_exempt(views.getCategory), name='getCategory'),
    path('categories/', views.Categories, name='categories'),
    path('add/category/', views.addCategory, name='addCategory'),
    path('edit/category/', views.editCategory, name='editCategory'),
    path('delete/category/', views.deleteCategory, name='deleteCategory'),
    path('stats/expense-category-summary/', views.expenseCategorySummary,
         name='expenseCategorySummary'),
    path('stats/expense-category-line-summary/', views.expenseCategoryLineSummary,
         name='expenseCategoryLineSummary'),
    path('export-csv/', views.exportCsv, name='exportCsv'),
    path('export-excel/', views.exportExcel, name='exportExcel'),
]

settings/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('expense.urls')),
    path('authentication/', include('authentication.urls')),
    path('userpreferences/', include('userpreferences.urls')),
    path('userincome/', include('userincome.urls')),
]

userincome/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from . import views

app_name = 'income'

urlpatterns = [
    path('', views.home, name='home'),
    path('add/income/', views.addIncome, name='addIncome'),
    path('edit/income/<int:id>/', views.editIncome, name='editIncome'),
    path('delete/income/<int:id>/', views.deleteIncome, name='deleteIncome'),
    path('search-incomes/', csrf_exempt(views.searchIncome), name='searchIncome'),
    path('get-source/<int:source_id>/',
         csrf_exempt(views.getSource), name='getSource'),
    path('source/', views.Sources, name='source'),
    path('add/source/', views.AddSource, name='AddSource'),
    path('edit/source/', views.editSource, name='editSource'),
    path('delete/source/', views.deleteSource, name='deleteSource'),
    path('stats/income-source-line-summary/', views.expenseSourceLineSummary,
         name='incomeSourceLineSummary'),
    path('stats/income-source-summary/', views.expenseSourceSummary,
         name='incomeSourceSummary'),
    path('export-csv/', views.exportCsv, name='exportCsv'),
    path('export-excel/', views.exportExcel, name='exportExcel'),
]

userpreferences/urls.py
from django.urls import path

from . import views

app_name = 'userpreferences'

urlpatterns = [
    path('preferences/', views.preferences, name='preferences'),
]

templates/partials/_footer.html
{% load static %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js">
</script><script src="{% static 'assets/custom/js/main.js' %} "></script>

templates/partials/_head.html
{% load static %}


<script src="{% static 'assets/custom/js/color-modes.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.3.2/dist/chart.umd.min.js"></script>
<!-- Custom styles for this template -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
<!-- Custom styles for this template -->
<link rel="stylesheet" href="{% static 'assets/custom/css/boostrap.min.css'%}"  >
<link rel="stylesheet" href="{% static 'assets/custom/css/dashboard.css' %}"  />
<link rel="stylesheet" href="{% static 'assets/custom/css/main.css' %} />

templates/partials/_header.html
<header class="navbar sticky-top bg-dark flex-md-nowrap p-0 shadow" data-bs-theme="dark">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6 text-white" href="{% url 'expense:home' %}">Control Expense</a>
    <ul class="navbar-nav flex-row d-md-none">
        <li class="nav-item text-nowrap">
          <button class="nav-link px-3 text-white" type="button" data-bs-toggle="offcanvas" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <svg class="bi"><use xlink:href="#list"><i class="bi bi-list"></i></use></svg>
          </button>
        </li>
      </ul>
</header>

templates/partials/_messages.html
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
{% if messages %}
    {% for message in messages %}
        <script>
            swal({
                text: "{{ message }}",
                icon: "{{ message.tags }}",
              });
        </script>
    {% endfor %}
{% endif %}

templates/partials/_navbar.html
<div class="sidebar border border-right col-md-3 col-lg-2 p-0 bg-body-tertiary">
    <div class="offcanvas-lg offcanvas-end bg-body-tertiary" tabindex="-1" id="sidebarMenu" aria-labelledby="sidebarMenuLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="sidebarMenuLabel">Control Expenses</h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#sidebarMenu" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body d-md-flex flex-column p-0 pt-lg-3 overflow-y-auto">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2 active" aria-current="page" href="{% url 'expense:home' %}">
              <svg class="bi">
                <use xlink:href="#house-fill" />
              </svg>Dashboard
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2" href="{% url 'expense:home' %}">
              <svg class="bi">
                <use xlink:href="#file-earmark" />
              </svg>Expense
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2" href="{% url 'income:home' %}">
              <svg class="bi">
                <use xlink:href="#cart" />
              </svg>Income
            </a>
          </li>

        <hr class="my-3" />
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2" href="{% url 'expense:categories' %}">
              Category
            </a>
          </li>          
          <li class="nav-item">
            <a class="nav-link d-flex align-items-center gap-2" href="{% url 'income:source' %}">
              Source
            </a>
          </li>
        </ul>
        <hr class="my-3" />

        <li class="nav-item">
          <a class="nav-link d-flex align-items-center gap-2" href="{% url 'userpreferences:preferences' %}">
            <svg class="bi">
              <use xlink:href="#gear-wide-connected" />
            </svg>Settings
          </a>
        </li>
        <h6
      class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted"
    >
    </h6>
        <ul class="nav flex-column mb-auto">
          <li class="nav-item">
            <form action="{% url 'authentication:logout' %}" method="post">
              {% csrf_token %}
                <input class="nav-link d-flex align-items-center gap-2" type="submit" value="Sign out">
            </form>
          </li>
        </ul>
      </div>
    </div>
  </div>