expense/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from . import views

app_name = 'expense'

urlpatterns = [
    path('', views.home, name='home'),
    path('add/expense/', views.addExpense, name='addExpense'),
    path('edit/expense/<int:id>/', views.editExpense, name='editExpense'),
    path('delete/expense/<int:id>/', views.deleteExpense, name='deleteExpense'),
    path('search-expenses/', csrf_exempt(views.searchExpense), name='searchExpense'),
    path('get-category/<int:category_id>/',
         csrf_exempt(views.getCategory), name='getCategory'),
    path('categories/', views.Categories, name='categories'),
    path('add/category/', views.addCategory, name='addCategory'),
    path('edit/category/', views.editCategory, name='editCategory'),
    path('delete/category/', views.deleteCategory, name='deleteCategory'),
    path('stats/expense-category-summary/', views.expenseCategorySummary,
         name='expenseCategorySummary'),
    path('stats/expense-category-line-summary/', views.expenseCategoryLineSummary,
         name='expenseCategoryLineSummary'),
    path('export-csv/', views.exportCsv, name='exportCsv'),
    path('export-excel/', views.exportExcel, name='exportExcel'),
]

settings/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('expense.urls')),
    path('authentication/', include('authentication.urls')),
    path('userpreferences/', include('userpreferences.urls')),
    path('userincome/', include('userincome.urls')),
]

userincome/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from . import views

app_name = 'income'

urlpatterns = [
    path('', views.home, name='home'),
    path('add/income/', views.addIncome, name='addIncome'),
    path('edit/income/<int:id>/', views.editIncome, name='editIncome'),
    path('delete/income/<int:id>/', views.deleteIncome, name='deleteIncome'),
    path('search-incomes/', csrf_exempt(views.searchIncome), name='searchIncome'),
    path('get-source/<int:source_id>/',
         csrf_exempt(views.getSource), name='getSource'),
    path('source/', views.Sources, name='source'),
    path('add/source/', views.AddSource, name='AddSource'),
    path('edit/source/', views.editSource, name='editSource'),
    path('delete/source/', views.deleteSource, name='deleteSource'),
    path('stats/income-source-line-summary/', views.expenseSourceLineSummary,
         name='incomeSourceLineSummary'),
    path('stats/income-source-summary/', views.expenseSourceSummary,
         name='incomeSourceSummary'),
    path('export-csv/', views.exportCsv, name='exportCsv'),
    path('export-excel/', views.exportExcel, name='exportExcel'),
]

userincome/models.py
# Create your models here.
from django.contrib.auth.models import User
from django.db import models


class Source(models.Model):
    name = models.CharField(max_length=255)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Sources'


class UserIncome(models.Model):
    amount = models.FloatField()
    description = models.CharField(max_length=255)
    date = models.DateField(auto_now_add=True)
    source = models.ForeignKey('Source', on_delete=models.CASCADE)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)

    def __str__(self):
        return self.description + ' - ' + str(self.amount)

    class Meta:
        ordering = ['-date']

userincome/views.py
import calendar
import csv
import datetime
import json

import xlwt
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import Http404, HttpResponse, JsonResponse
from django.shortcuts import redirect, render

from userpreferences.models import UserPreference

from .models import Source, UserIncome

# Create your views here.


@login_required(login_url='authentication:login', redirect_field_name='next')
def getSource(request, source_id):
    sources = Source.objects.get(id=source_id, user=request.user)
    data = {
        'name': sources.name,
    }
    return JsonResponse(data)


@login_required(login_url='authentication:login', redirect_field_name='next')
def searchIncome(request):
    if request.method == 'POST':
        search_str = json.loads(request.body).get('searchText')
        income = UserIncome.objects.filter(
            Q(amount__istartswith=search_str) | Q(date__istartswith=search_str) |
            Q(description__icontains=search_str) | Q(
                source__name__icontains=search_str),
            user=request.user
        )
        data = income.values()
        return JsonResponse(list(data), safe=False)


@login_required(login_url='authentication:login', redirect_field_name='next')
def home(request):
    source = Source.objects.filter(user=request.user)
    incomes = UserIncome.objects.filter(user=request.user)
    paginator = Paginator(incomes, 10)
    page_number = request.GET.get('page')
    page_obj = Paginator.get_page(paginator, page_number)

    currency = UserPreference.objects.get(user=request.user).currency

    if not source:
        messages.error(
            request, 'You have not added any source yet. Please add a source first.')
        return redirect('income:source')

    context = {
        'source': source,
        'incomes': incomes,
        'page_obj': page_obj,
        'currency': currency
    }

    return render(request, 'income/pages/home.html', context)


@login_required(login_url='authentication:login', redirect_field_name='next')
def addIncome(request):
    template_name = 'income/pages/addIncome.html'
    sources = Source.objects.filter(user=request.user)
    context = {
        'sources': sources,
        'values': request.POST
    }
    if request.method == 'GET':
        return render(request, template_name, context)

    if request.method == 'POST':
        amount = request.POST['amount']

        if not amount:
            messages.error(request, 'Amount is required')
            return render(request, template_name, context)

        description = request.POST['description']
        date = request.POST['income_date']
        source = request.POST['source']

        source = Source.objects.get(id=source)

        if not description:
            messages.error(request, 'description is required')
            return render(request, template_name, context)

        UserIncome.objects.create(user=request.user, amount=amount, date=date,
                                  source=source, description=description)
        messages.success(request, 'Income saved successfully')

        return redirect('income:home')


@login_required(login_url='authentication:login', redirect_field_name='next')
def editIncome(request, id):
    template_name = 'income/pages/editIncome.html'
    income = UserIncome.objects.get(pk=id, user=request.user)
    sources = Source.objects.filter(user=request.user)

    context = {
        'income': income,
        'values': income,
        'sources': sources
    }
    if request.method == 'GET':
        return render(request, template_name, context)

    if request.method == 'POST':
        amount = request.POST['amount']

        if not amount:
            messages.error(request, 'Amount is required')
            return render(request, template_name, context)

        description = request.POST['description']
        date = request.POST['income_date']
        source = request.POST['source']

        source = Source.objects.get(id=source)

        if not description:
            messages.error(request, 'description is required')
            return render(request, template_name, context)

        income.amount = amount
        income.date = date
        income.source = source
        income.description = description
        income.save()
        messages.success(request, 'Income updated successfully')

        return redirect('income:home')


@login_required(login_url='authentication:login', redirect_field_name='next')
def deleteIncome(request, id):
    income = UserIncome.objects.get(pk=id, user=request.user)
    income.delete()
    messages.success(request, 'Income deleted successfully')

    return redirect('income:home')


@login_required(login_url='authentication:login', redirect_field_name='next')
def Sources(request):
    sources = Source.objects.filter(user=request.user)
    return render(request, 'income/pages/source.html', {'sources': sources})


@login_required(login_url='authentication:login', redirect_field_name='next')
def AddSource(request):
    if not request.POST:
        raise Http404()

    if request.method == 'POST':
        name = request.POST['name']

        if not name:
            messages.error(request, 'Source is required')
            return redirect('income:source')

        if Source.objects.filter(name=name).exists():
            messages.error(request, 'Source already exists')
            return redirect('income:source')

        Source.objects.create(user=request.user, name=name)
        messages.success(request, 'Source saved successfully')

        return redirect('income:source')


@login_required(login_url='authentication:login', redirect_field_name='next')
def editSource(request):
    if not request.POST:
        raise Http404()

    id = request.POST.get('source_id')

    if request.method == 'POST':
        source = Source.objects.get(pk=id, user=request.user)
        name = request.POST['name']

        if not request.POST['name']:
            messages.error(request, 'Source is required')
            return redirect('income:source')

        if Source.objects.filter(name=name).exists():
            messages.error(request, 'Source already exists')
            return redirect('income:source')

        source.name = name
        source.save()
        messages.success(request, 'Source updated successfully')

        return redirect('income:source')


@login_required(login_url='authentication:login', redirect_field_name='next')
def deleteSource(request):
    if not request.POST:
        raise Http404()

    id = request.POST.get('source_id')

    source = Source.objects.get(pk=id, user=request.user)
    source.delete()
    messages.success(request, 'Source deleted successfully')

    return redirect('income:source')


@login_required(login_url='authentication:login', redirect_field_name='next')
def expenseSourceLineSummary(request):
    todays_date = datetime.date.today()
    five_months_ago = todays_date - datetime.timedelta(days=30 * 5)
    # date__gte = greater than or equal to, (maiores ou iguais)
    # date__lte = less than or equal to, (menores ou iguais)
    incomes = UserIncome.objects.filter(
        date__gte=five_months_ago, date__lte=todays_date, user=request.user)

    finalrep = {}
    # Calculate the incomes for each month and store them in finalrep dictionary
    for income in incomes:
        month_year = f'{income.date.year}-{income.date.month:02}'
        finalrep[month_year] = finalrep.get(month_year, 0) + income.amount

    labels = []
    current_month = five_months_ago.month
    current_year = five_months_ago.year

    for i in range(6):  # Include the current month + 5 previous months
        month_name = calendar.month_name[current_month]
        labels.append(f'{month_name} {current_year}')
        if current_month == 12:
            current_month = 1
            current_year += 1
        else:
            current_month += 1

    data = []

    for label in labels:
        month, year = label.split()
        month_number = list(calendar.month_name).index(month)
        month_year = f'{year}-{month_number:02}'
        amount = finalrep.get(month_year, 0)
        data.append(amount)

    return JsonResponse({'labels': labels, 'data': data})


@login_required(login_url='authentication:login', redirect_field_name='next')
def expenseSourceSummary(request):
    todays_date = datetime.date.today()
    six_months_ago = todays_date - datetime.timedelta(days=30*6)
    incomes = UserIncome.objects.filter(date__gte=six_months_ago,
                                        date__lte=todays_date, user=request.user)
    finalrep = {}

    def get_income_source_amount(source_id):
        amount = 0
        filtered_by_source = incomes.filter(source_id=source_id)

        for item in filtered_by_source:
            amount += item.amount

        return amount

    for income in incomes:
        source_id = income.source.id
        source_name = income.source.name
        finalrep[source_name] = get_income_source_amount(source_id)

    return JsonResponse({'income_source_data': finalrep})


@login_required(login_url='authentication:login', redirect_field_name='next')
def exportCsv(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename=Incomes' + \
        str(datetime.datetime.now())+'.csv'

    # módulo usada para criar um objeto gravador CSV
    writer = csv.writer(response)

    # gravar linhas de dados no arquivo CSV
    writer.writerow(['Amount', 'Description', 'Source', 'Date'])

    incomes = UserIncome.objects.filter(user=request.user)

    for income in incomes:
        writer.writerow([income.amount, income.description,
                         income.source, income.date])

    return response


@login_required(login_url='authentication:login', redirect_field_name='next')

userincome/templates/income/pages/addIncome.html
{% extends 'base.html' %} 
{% block title %}Add Income{% endblock title %}

{% block content %}

<div class="container mt-4">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <a href="{% url 'income:home'%}">Incomes</a>
      </li>
      <li class="breadcrumb-item active" aria-current="page">Add Incomes</li>
    </ol>
  </nav>

  <div class="card">
    <div class="card-body">
      <form action="{% url 'income:addIncome' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
          <label for="">Amount</label>
          <input
            type="text"
            class="form-control form-control-sm"
            name="amount"
            value="{{values.amount}}"
          />
        </div>
        <div class="form-group">
          <label for="">Description</label>
          <input
            type="text"
            class="form-control form-control-sm"
            name="description"
            value="{{values.description}}"
          />
        </div>
        <div class="form-group">
          <label for="">Sources</label>
          <select class="form-control" name="source">
            {% for source in sources%}
            <option name="source" value="{{source.id}}"
              >{{source.name}}</option
            >

            {% endfor %}
          </select>
        </div>
        <div class="form-group">
          <label for="">Date of Income</label>
          <input
            type="date"
            class="form-control form-control-sm"
            name="income_date"
          />
        </div>

        <input
          type="submit"
          value="Submit"
          class="btn btn-primary btn-primary-sm mt-2"
        />
      </form>
    </div>
  </div>
</div>

{% endblock %}

userincome/templates/income/pages/editIncome.html
{% extends 'base.html' %} 
{% block title %}Edit Income{% endblock title %}

{% block content %}

<div class="container mt-4">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <a href="{% url 'income:home'%}">Incomes</a>
      </li>
      <li class="breadcrumb-item active" aria-current="page">Edit Incomes</li>
    </ol>
  </nav>

  <div class="card">
    <div class="card-body">
      <form action="{% url 'income:editIncome' income.id %}" method="post">
        {% csrf_token %}
        <div class="form-group">
          <label for="">Amount</label>
          <input
            type="text"
            class="form-control form-control-sm"
            name="amount"
            value="{{values.amount}}"
          />
        </div>
        <div class="form-group">
          <label for="">Description</label>
          <input
            type="text"
            class="form-control form-control-sm"
            name="description"
            value="{{values.description}}"
          />
        </div>
        <div class="form-group">
          <label for="">Source</label>
          <select class="form-control" name="source">
            {% for source in sources%}
            <option  value="{{source.id}}" {% if source.id == income.source.id %}selected{% endif %}>{{source.name}}</option>

            {% endfor %}
          </select>
        </div>
        <div class="form-group">
          <label for="">Date of Income</label>
          <input
            type="date"
            class="form-control form-control-sm"
            name="income_date"
            value="{{ values.date|date:'Y-m-d' }}"
          />
        </div>
        <input
          type="submit"
          value="Submit"
          class="btn btn-primary btn-primary-sm mt-2"
        />
      </form>
    </div>
  </div>
</div>

{% endblock %}

userincome/templates/income/pages/home.html
{% extends 'base.html' %}
{% block title %} Income {% endblock %} 
{% load static %}
{% block content %}
  <div class="container mt-4">
    <div class="row">
      <div class="col-md-10">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="#">Home</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">My Income</li>
          </ol>
        </nav>
      </div>
      <div class="col-md-2">
        <a href="{% url 'income:addIncome' %}" class="btn btn-primary">Add Income</a>
      </div>
    </div>
  </div>


  <div class="container mt-4">
    <div class="row">
        <form action="{% url 'income:searchIncome' %}" method="POST">
          <div class="input-group mb-3">
            <input
              type="text"
              class="form-control"
              id="searchField"
              placeholder="Search Income"
            />
          </div>
        </form>
    </div>
    <div class="container text-center">
      <div class="row align-items-center">

        <div class="col">
          <a class="btn btn-outline-primary" href="{% url 'income:exportCsv' %}">Export CSV</a>
        </div>        

        <div class="col">
          <a class="btn btn-outline-secondary" href="{% url 'income:exportExcel' %}">Export Excel</a>
        </div>        
      </div>
    </div>
  </div>

  {% if  page_obj%} 
    <div class="container mt-4">
      <div class="row">
        <div class="col-md-6 col-sm-6 col-xs-12">
          <div class="x_panel">
            <div class="x_content">
              <canvas id="myChart"></canvas>
            </div>
          </div>
    
        </div>    
        <div class="col-md-6 col-sm-6 col-xs-12">
          <div class="x_panel">
            <div class="x_content">
              <canvas id="myChart2"></canvas>
            </div>
          </div>
        </div>
      </div>
    </div>
  {%endif%}

  <div class="container mt-4">
    <div class="table-responsive app-table">  

      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Amount ({{currency}})</th>
            <th class="d-none d-md-table-cell">Source</th>
            <th>Description</th>
            <th>Date</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {% for income in page_obj %}
          <tr>
            <td>{{income.amount}}</td>
            <td class="d-none d-md-table-cell">{{income.source}}</td>
            <td>{{income.description}}</td>
            <td>{{income.date}}</td>
            <td>
              <a
                href="{% url 'income:editIncome' income.id %}"
                class="btn btn-primary btn-sm"
                >Edit</a
              >
              <a
                href="{% url 'income:deleteIncome' income.id %}"
                class="btn btn-danger btn-sm"
                >Delete</a
              >
            </td>
          </tr>

          {%empty%}
          <tr>
            <td colspan="5">No income Found</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>


    <p class="no-results" style="display: none;">No results </p>
    <div class="table-output">


      <table class="table table-stripped table-hover">
        <thead>
          <tr>
            <th>Amount ({{currency}})</th>
            <th>Category</th>
            <th>Description</th>
            <th>Date</th>
            <th></th>
          </tr>
        </thead>

        <tbody  class="table-body">


        </tbody>
      </table>
    </div>


    {% if page_obj %}
    <div class="pagination-container">
      <div class="container mt-4">
        showing page {{page_obj.number}} of {{page_obj.paginator.num_pages}} pages
      </div>
      
      <ul class="pagination align-right float-right mr-auto">
        {% if page_obj.has_previous %}
        <li {% if page_obj.number == 1 %} class="page-item active" {% endif %}><a class="page-link" href="?page=1">&laquo; 1</a></li>
        <li class="page-item"> <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
        {% endif %}
        
        {% if page_obj.has_next %}
        <li class="page-item"> <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
        <li class="page-item"> <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages}} &raquo;</a></li>
        {% endif %}
      </ul>
    </div>
    {% endif %}
  </div>
  <script src="{% static 'assets/custom/js/searchincome.js' %}"></script>
  <script src="{% static 'assets/custom/js/statsIncome.js' %}"></script>
{% endblock %}

userincome/templates/income/pages/source.html
{% extends 'base.html' %} {% block title %}Sources{% endblock title %} 
{%block content %}
    <div class="container mt-4">
    <div class="row">
        <div class="col-md-10">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="#">Home</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">
                My Sources
            </li>
            </ol>
        </nav>
        </div>
        <div class="col-md-2">
            {% include 'income/pages/partialmodal/createSource.html' %}
        </div>
    </div>
    </div>

    <div class="container mt-4">
        <div class="row row-cols-1 row-cols-md-2 g-4">
            {% for source in sources %}
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ source.name }}</h5>
                        <button type="button" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#editModal{{ source.id }}">Edit</button>
                        <button type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#deleteModal{{ source.id }}">Delete</button>
                    </div>
                </div>
            </div>
            {% include 'income/pages/partialmodal/editSource.html' %}
            {% include 'income/pages/partialmodal/deleteSource.html' %}
            {% empty %}
            <h1>
                No Sources.
            </h1>
            {% endfor %}
        </div>
    </div>

{% endblock content %}