expense/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from . import views

app_name = 'expense'

urlpatterns = [
    path('', views.home, name='home'),
    path('add/expense/', views.addExpense, name='addExpense'),
    path('edit/expense/<int:id>/', views.editExpense, name='editExpense'),
    path('delete/expense/<int:id>/', views.deleteExpense, name='deleteExpense'),
    path('search-expenses/', csrf_exempt(views.searchExpense), name='searchExpense'),
    path('get-category/<int:category_id>/',
         csrf_exempt(views.getCategory), name='getCategory'),
    path('categories/', views.Categories, name='categories'),
    path('add/category/', views.addCategory, name='addCategory'),
    path('edit/category/', views.editCategory, name='editCategory'),
    path('delete/category/', views.deleteCategory, name='deleteCategory'),
    path('stats/expense-category-summary/', views.expenseCategorySummary,
         name='expenseCategorySummary'),
    path('stats/expense-category-line-summary/', views.expenseCategoryLineSummary,
         name='expenseCategoryLineSummary'),
    path('export-csv/', views.exportCsv, name='exportCsv'),
    path('export-excel/', views.exportExcel, name='exportExcel'),
]

settings/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('expense.urls')),
    path('authentication/', include('authentication.urls')),
    path('userpreferences/', include('userpreferences.urls')),
    path('userincome/', include('userincome.urls')),
]

expense/models.py
# Create your models here.
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=255)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Categories'


class Expense(models.Model):
    amount = models.FloatField()
    description = models.CharField(max_length=255)
    date = models.DateField(auto_now_add=True)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)

    def __str__(self):
        return self.description + ' - ' + str(self.amount)

    class Meta:
        ordering = ['-date']

expense/views.py
import calendar
import csv
import datetime
import json

import xlwt
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import Http404, HttpResponse, JsonResponse
from django.shortcuts import redirect, render

from userpreferences.models import UserPreference

from .models import Category, Expense

# Create your views here.


def getCategory(request, category_id):
    categories = Category.objects.get(id=category_id, user=request.user)
    data = {
        'name': categories.name,
    }
    return JsonResponse(data)


def searchExpense(request):
    if request.method == 'POST':
        search_str = json.loads(request.body).get('searchText')
        expenses = Expense.objects.filter(
            Q(amount__istartswith=search_str) | Q(date__istartswith=search_str) |
            Q(description__icontains=search_str) | Q(
                category__name__icontains=search_str),
            user=request.user
        )
        data = expenses.values()
        return JsonResponse(list(data), safe=False)


@login_required(login_url='authentication:login', redirect_field_name='next')
def home(request):
    categories = Category.objects.filter(user=request.user)
    expenses = Expense.objects.filter(user=request.user)
    paginator = Paginator(expenses, 10)
    page_number = request.GET.get('page')
    page_obj = Paginator.get_page(paginator, page_number)

    currency = UserPreference.objects.get(user=request.user).currency

    if not categories.exists():
        messages.info(
            request, 'You have not created any category yet. Please create a category first')
        return redirect('expense:categories')

    context = {
        'categories': categories,
        'expenses': expenses,
        'page_obj': page_obj,
        'currency': currency
    }

    return render(request, 'expense/pages/home.html', context)


@login_required(login_url='authentication:login', redirect_field_name='next')
def addExpense(request):
    template_name = 'expense/pages/addExpense.html'
    categories = Category.objects.filter(user=request.user)
    context = {
        'categories': categories,
        'values': request.POST
    }
    if request.method == 'GET':
        return render(request, template_name, context)

    if request.method == 'POST':
        amount = request.POST['amount']

        if not amount:
            messages.error(request, 'Amount is required')
            return render(request, template_name, context)

        description = request.POST['description']
        date = request.POST['expense_date']
        category = request.POST['category']

        category = Category.objects.get(id=category)

        if not description:
            messages.error(request, 'description is required')
            return render(request, template_name, context)

        Expense.objects.create(user=request.user, amount=amount, date=date,
                               category=category, description=description)
        messages.success(request, 'Expense saved successfully')

        return redirect('expense:home')


@login_required(login_url='authentication:login', redirect_field_name='next')
def editExpense(request, id):
    template_name = 'expense/pages/editExpense.html'
    expense = Expense.objects.get(pk=id, user=request.user)
    categories = Category.objects.filter(user=request.user)

    context = {
        'expense': expense,
        'values': expense,
        'categories': categories
    }

    if request.method == 'GET':
        return render(request, template_name, context)

    if request.method == 'POST':
        amount = request.POST['amount']

        if not amount:
            messages.error(request, 'Amount is required')
            return render(request, template_name, context)

        description = request.POST['description']
        date = request.POST['expense_date']
        category = request.POST['category']

        category = Category.objects.get(id=category)

        if not description:
            messages.error(request, 'description is required')
            return render(request, template_name, context)

        expense.amount = amount
        expense.date = date
        expense.category = category
        expense.description = description
        expense.save()
        messages.success(request, 'Expense updated successfully')

        return redirect('expense:home')


@login_required(login_url='authentication:login', redirect_field_name='next')
def deleteExpense(request, id):
    expense = Expense.objects.get(pk=id, user=request.user)
    expense.delete()
    messages.success(request, 'Expense deleted successfully')

    return redirect('expense:home')


@login_required(login_url='authentication:login', redirect_field_name='next')
def Categories(request):
    categories = Category.objects.filter(user=request.user)
    return render(request, 'expense/pages/categories.html', {'categories': categories})


@login_required(login_url='authentication:login', redirect_field_name='next')
def addCategory(request):
    if not request.POST:
        raise Http404()

    if request.method == 'POST':
        name = request.POST['name']

        if not name:
            messages.error(request, 'Category is required')
            return redirect('expense:categories')

        if Category.objects.filter(user=request.user, name=name).exists():
            messages.error(request, 'Category already exists')
            return redirect('expense:categories')

        Category.objects.create(user=request.user, name=name)
        messages.success(request, 'Category saved successfully')

        return redirect('expense:categories')


@login_required(login_url='authentication:login', redirect_field_name='next')
def editCategory(request):
    if not request.POST:
        raise Http404()

    id = request.POST.get('category_id')
    name = request.POST.get('name')

    if request.method == 'POST':
        category = Category.objects.get(pk=id, user=request.user)

        if not category:
            messages.error(request, 'Category not found')
            return redirect('expense:categories')

        if Category.objects.filter(user=request.user, name=name).exists():
            messages.error(request, 'Category already exists')
            return redirect('expense:categories')

        category.name = name
        category.save()
        messages.success(request, 'Category updated successfully')

        return redirect('expense:categories')


@login_required(login_url='authentication:login', redirect_field_name='next')
def deleteCategory(request):
    if not request.POST:
        raise Http404()

    id = request.POST.get('category_id')
    category = Category.objects.get(pk=id, user=request.user)
    category.delete()
    messages.success(request, 'Category deleted successfully')

    return redirect('expense:categories')


@login_required(login_url='authentication:login', redirect_field_name='next')
def expenseCategoryLineSummary(request):
    todays_date = datetime.date.today()
    five_months_ago = todays_date - datetime.timedelta(days=30 * 5)
    # date__gte = greater than or equal to, (maiores ou iguais)
    # date__lte = less than or equal to, (menores ou iguais)
    expenses = Expense.objects.filter(
        date__gte=five_months_ago, date__lte=todays_date, user=request.user)

    finalrep = {}
    # Calculate the expenses for each month and store them in finalrep dictionary
    for expense in expenses:
        month_year = f'{expense.date.year}-{expense.date.month:02}'
        finalrep[month_year] = finalrep.get(month_year, 0) + expense.amount

    labels = []
    current_month = five_months_ago.month
    current_year = five_months_ago.year

    for i in range(6):  # Include the current month + 5 previous months
        month_name = calendar.month_name[current_month]
        labels.append(f'{month_name} {current_year}')
        if current_month == 12:
            current_month = 1
            current_year += 1
        else:
            current_month += 1

    data = []

    for label in labels:
        month, year = label.split()
        month_number = list(calendar.month_name).index(month)
        month_year = f'{year}-{month_number:02}'
        amount = finalrep.get(month_year, 0)
        data.append(amount)

    return JsonResponse({'labels': labels, 'data': data})


@login_required(login_url='authentication:login', redirect_field_name='next')
def expenseCategorySummary(request):
    todays_date = datetime.date.today()
    six_months_ago = todays_date - datetime.timedelta(days=30*6)
    expenses = Expense.objects.filter(date__gte=six_months_ago,
                                      date__lte=todays_date, user=request.user)
    finalrep = {}

    def get_expense_category_amount(category_id):
        amount = 0
        filtered_by_category = expenses.filter(category_id=category_id)

        for item in filtered_by_category:
            amount += item.amount

        return amount

    for expense in expenses:
        category_id = expense.category.id
        category_name = expense.category.name
        finalrep[category_name] = get_expense_category_amount(category_id)

    return JsonResponse({'expense_category_data': finalrep})


@login_required(login_url='authentication:login', redirect_field_name='next')
def exportCsv(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename=Expenses' + \
        str(datetime.datetime.now())+'.csv'

    # módulo usada para criar um objeto gravador CSV
    writer = csv.writer(response)

    # gravar linhas de dados no arquivo CSV
    writer.writerow(['Amount', 'Description', 'Category', 'Date'])

    expenses = Expense.objects.filter(user=request.user)

    for expense in expenses:
        writer.writerow([expense.amount, expense.description,

expense/templates/expense/pages/addExpense.html
{% extends 'base.html' %} 
{% block title %}Add Expense{% endblock title %}

{% block content %}

<div class="container mt-4">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <a href="{% url 'expense:home'%}">Expenses</a>
      </li>
      <li class="breadcrumb-item active" aria-current="page">Add Expenses</li>
    </ol>
  </nav>

  <div class="card">
    <div class="card-body">
      <form action="{% url 'expense:addExpense' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
          <label for="">Amount</label>
          <input
            type="text"
            class="form-control form-control-sm"
            name="amount"
            value="{{values.amount}}"
          />
        </div>
        <div class="form-group">
          <label for="">Description</label>
          <input
            type="text"
            class="form-control form-control-sm"
            name="description"
            value="{{values.description}}"
          />
        </div>
        <div class="form-group">
          <label for="">Category</label>
          <select class="form-control" name="category">
            {% for category in categories%}
            <option name="category" value="{{category.id}}"
              >{{category.name}}</option
            >

            {% endfor %}
          </select>
        </div>
        <div class="form-group">
          <label for="">Date of Expense</label>
          <input
            type="date"
            class="form-control form-control-sm"
            name="expense_date"
          />
        </div>

        <input
          type="submit"
          value="Submit"
          class="btn btn-primary btn-primary-sm mt-2"
        />
      </form>
    </div>
  </div>
</div>

{% endblock %}

expense/templates/expense/pages/categories.html
{% extends 'base.html' %} {% block title %}Categories{% endblock title %} 
{%block content %}
    <div class="container mt-4">
    <div class="row">
        <div class="col-md-10">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="#">Home</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">
                My Categories
            </li>
            </ol>
        </nav>
        </div>
        <div class="col-md-2">
            {% include 'expense/pages/partialmodal/createCategory.html' %}
        </div>
    </div>
    </div>

    <div class="container mt-4">
        <div class="row row-cols-1 row-cols-md-2 g-4">
            {% for category in categories %}
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ category.name }}</h5>
                        <button type="button" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#editModal{{ category.id }}">Edit</button>
                        <button type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#deleteModal{{ category.id }}">Delete</button>
                    </div>
                </div>
            </div>
            {% include 'expense/pages/partialmodal/editCategory.html' %}
            {% include 'expense/pages/partialmodal/deleteCategory.html' %}
            {% empty %}
            <h1>
                No categories.
            </h1>
            {% endfor %}
        </div>
    </div>

{% endblock content %}

expense/templates/expense/pages/editExpense.html
{% extends 'base.html' %} 
{% block title %}Edit Expense{% endblock title %}

{% block content %}

<div class="container mt-4">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <a href="{% url 'expense:home'%}">Expenses</a>
      </li>
      <li class="breadcrumb-item active" aria-current="page">Edit Expenses</li>
    </ol>
  </nav>

  <div class="card">
    <div class="card-body">
      <form action="{% url 'expense:editExpense' expense.id %}" method="post">
        {% csrf_token %}
        <div class="form-group">
          <label for="">Amount</label>
          <input
            type="text"
            class="form-control form-control-sm"
            name="amount"
            value="{{values.amount}}"
          />
        </div>
        <div class="form-group">
          <label for="">Description</label>
          <input
            type="text"
            class="form-control form-control-sm"
            name="description"
            value="{{values.description}}"
          />
        </div>
        <div class="form-group">
          <label for="">Category</label>
          <select class="form-control" name="category">
            {% for category in categories %}
              <option value="{{ category.id }}" {% if category.id == expense.category.id %}selected{% endif %}>
                {{ category.name }}
              </option>
            {% endfor %}
          </select>
        </div>
        
        
        <div class="form-group">
          <label for="">Date of Expense</label>
          <input
            type="date"
            class="form-control form-control-sm"
            name="expense_date"
            value="{{ values.date|date:'Y-m-d' }}"
          />
        </div>
        <input
          type="submit"
          value="Submit"
          class="btn btn-primary btn-primary-sm mt-2"
        />
      </form>
    </div>
  </div>
</div>

{% endblock %}

expense/templates/expense/pages/home.html
{% extends 'base.html' %}
{% block title %} Home {% endblock %} 
{% load static %}
{% block content %}
  <div class="container mt-4">
    <div class="row">
      <div class="col-md-10">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="#">Home</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">My Expense</li>
          </ol>
        </nav>
      </div>
      <div class="col-md-2">
        <a href="{% url 'expense:addExpense' %}" class="btn btn-primary">Add Expense</a>
      </div>
    </div>
  </div>

  <div class="container mt-4">
    <div class="row">
        <form action="{% url 'expense:searchExpense' %}" method="POST">
          <div class="input-group mb-3">
            <input
              type="text"
              class="form-control"
              id="searchField"
              placeholder="Search Expense"
            />
          </div>
        </form>
    </div>

    <div class="container text-center">
      <div class="row align-items-center">

        <div class="col">
          <a class="btn btn-outline-primary" href="{% url 'expense:exportCsv' %}">Export CSV</a>
        </div>        

        <div class="col">
          <a class="btn btn-outline-secondary" href="{% url 'expense:exportExcel' %}">Export Excel</a>
        </div>        
      </div>
    </div>
  </div>

  {% if  page_obj%}
    <div class="container mt-4">
      <div class="row">
        <div class="col-md-6 col-sm-6 col-xs-12">
          <div class="x_panel">
            <div class="x_content">
              <canvas id="myChart"></canvas>
            </div>
          </div>
          
        </div>    
        <div class="col-md-6 col-sm-6 col-xs-12">
          <div class="x_panel">
            <div class="x_content">
              <canvas id="myChart2"></canvas>
            </div>
          </div>
        </div>
      </div>
    </div>
  {% endif %}
  
  <div class="container mt-4">
    <div class="app-table">  

      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Amount ({{currency}})</th>
            <th class="d-none d-md-table-cell">Category</th>
            <th>Description</th>
            <th>Date</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {% for expense in page_obj %}
          <tr>
            <td>{{expense.amount}}</td>
            <td class="d-none d-md-table-cell">{{expense.category}}</td>
            <td>{{expense.description}}</td>
            <td>{{expense.date}}</td>
            <td>
              <a
                href="{% url 'expense:editExpense' expense.id %}"
                class="btn btn-primary btn-sm"
                >Edit</a
              >
              <a
                href="{% url 'expense:deleteExpense' expense.id %}"
                class="btn btn-danger btn-sm"
                >Delete</a
              >
            </td>
          </tr>

          {%empty%}
          <tr>
            <td colspan="5">No Expense Found</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>


    <p class="no-results" style="display: none;">No results </p>
    <div class="table-output">


      <table class="table table-stripped table-hover">
        <thead>
          <tr>
            <th>Amount ({{currency}})</th>
            <th>Category</th>
            <th>Description</th>
            <th>Date</th>
            <th></th>
          </tr>
        </thead>

        <tbody  class="table-body">


        </tbody>
      </table>
    </div>


    {% if page_obj %}
    <div class="pagination-container">
      <div class="container mt-4">
        showing page {{page_obj.number}} of {{page_obj.paginator.num_pages}} pages
      </div>
      
      <ul class="pagination align-right float-right mr-auto">
        {% if page_obj.has_previous %}
        <li {% if page_obj.number == 1 %} class="page-item active" {% endif %}><a class="page-link" href="?page=1">&laquo; 1</a></li>
        <li class="page-item"> <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
        {% endif %}
        
        {% if page_obj.has_next %}
        <li class="page-item"> <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
        <li class="page-item"> <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages}} &raquo;</a></li>
        {% endif %}
      </ul>
    </div>
    {% endif %}
  </div>
  <script src="{% static 'assets/custom/js/searchexpense.js' %}"></script>
  <script src="{% static 'assets/custom/js/statsExpense.js' %}"></script>
{% endblock %}